### ISSUE TITLE
Document Neptune & our SPARQL particulars

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/sparql-loader#10]
- SPARQL queries still must use HTTP POST
- When using CLI (curl), must prepend 'query=' or 'update=' (at least for Neptune / Blazegraph)
- For our message parsing, cannot use GRAPH and cannot insert newlines after {

**Comment by jcoyne** [comment]
@aaron-collier the last bullet is being fixed, right?

**Comment by aaron-collier** [comment]
@jcoyne yes. #13

**Comment by aaron-collier** [comment]
3rd bullet complete, The remainder captured in #245 and #246
