### ISSUE TITLE
Pass errors from Neptune through to clients

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/sparql-loader#14]
E.g., HTTP status codes and response bodies.

**Comment by jcoyne** [comment]
What sort of error codes are we talking about here? Is this the HTTP response status or something else?

**Comment by mjgiarlo** [comment]
@jcoyne Yep. Clarified above in description and title. Thanks!

**Comment by jcoyne** [comment]
Closed by https://github.com/sul-dlss-labs/sparql-loader/pull/20
