### ISSUE TITLE
Write integration tests with more complex data & expectations

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/sparql-loader#15]
Examples:

- SPARQL graph update
- SPARQL insert {} delete {} where {}
- SPARQL insert {}
- SPARQL query based on the above?

**Comment by aaron-collier** [comment]
Note, local integration testing of our current architecture does not seem to be supported through the use of LocalStack: https://github.com/localstack/localstack/issues/871

**Comment by aaron-collier** [comment]
Closed via sparql-loader/28
