### ISSUE TITLE
Implement health check for Neptune

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/sparql-loader#16]
Here or somewhere, have a health check with monitoring for Neptune

**Comment by aaron-collier** [comment]
See these metrics: https://docs.aws.amazon.com/neptune/latest/userguide/cloudwatch.html

and an example of how we can set the monitoring:

https://github.com/sul-dlss/terraform-module-aws-ecs/blob/master/service/cloudwatch.tf

**Comment by aaron-collier** [comment]
I've added a simple CloudWatch alert on the StatusErrors metric - https://github.com/sul-dlss/terraform-aws/blob/rialto-dev/organizations/development/rialto.tf#L217 I will add a new ticket to test this.
