### ISSUE TITLE
WIP: Does Neptune support Named Graphs?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/sparql-loader#9]
Recent SPARQL says not. If not, we need to rethink our source management plan.

**Comment by mjgiarlo** [comment]
FWIW, the Neptune Loader docs suggest that named graphs are support to *some* extent: https://docs.aws.amazon.com/neptune/latest/userguide/load-api-reference-load.html#load-api-reference-load-syntax

**Comment by cmh2166** [comment]
Yes it does. Samples in #dlss-rialto. Writing up wiki page on this now.
